### ISSUE TITLE
Help with Phpmyadmin on Heroku.

### ISSUE THREAD

**Issue by Adetona** [smsaladi/phpmyadmin_heroku#2]
Hello,

I found out this helpful repo on setting up phpmyadmin on Heroku https://github.com/smsaladi/phpmyadmin_heroku. But am kind of lost on how to set it up on my own Heroku setup. 

Do I need to copy your whole setup or there are some steps I have to take to make it work for me?

**Comment by smsaladi** [comment]
* Fork the repo
* Customize `config.inc.php` in the root of the repo to correspond to your mysql server ([instructions here](https://docs.phpmyadmin.net/en/latest/config.html))
* Start a new heroku app and point it towards your fork

**Comment by smsaladi** [comment]
Take a look here for the sample config:

https://github.com/smsaladi/phpmyadmin_heroku/blob/sample_cleardb/config.inc.php#L17-L36

The environment variables including 

* PHPMYADMIN_BLOWFISH_SECRET
* MYSQL_HOST
* MYSQL_USER
* MYSQL_PASSWORD

are all specified in [Heroku under config vars](https://devcenter.heroku.com/articles/config-vars)

**Comment by smsaladi** [comment]
@Adetona Did this work for you? If so, can you propose a revision to the README file that might help those potentially interested in the future?

**Comment by Adetona** [comment]
Sorry for the late reply.

I've not tried it out yet. When I do I will try making changes to the
ReadME.

Thanks for your help.

**Comment by nascimentorafael** [comment]
Hello @smsaladi 
I am trying to achieve the same as you have on https://phpmyadmin-heroku.herokuapp.com
However, I'm having some trouble with the `config.inc.php`.
How do I make to bypass the login?

I'm forking your project, setting the env variables and deploying, but I'm having an issue: `Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.`

Could you maybe share the file you are using on that Heroku app?

**Comment by smsaladi** [comment]
@nascimentorafael @Adetona Were you able to figure out your issues? Can you help @vbhusan?

#3

**Comment by nascimentorafael** [comment]
I was not able to figure the issue out. Please, let me know if any of you could.

**Comment by vbhusan** [comment]
> I was not able to figure the issue out. Please, let me know if any of you could.

I have applied the solution recently for my site on heroku.

**Comment by smsaladi** [comment]
Closing stale issue
